### ISSUE TITLE
Executor won't start when checkpoint is not configured

### ISSUE THREAD

**Issue by janisz** [allegro/mesos-executor#103]
```
panic: illegal value for minWait: 0s

goroutine 1 [running]:
github.com/allegro/mesos-executor/vendor/github.com/mesos/mesos-go/api/v1/lib/backoff.Notifier(0x3b9aca00, 0x0, 0x0, 0xc42039a840)
	$GOPATH/src/github.com/allegro/mesos-executor/vendor/github.com/mesos/mesos-go/api/v1/lib/backoff/backoff.go:58 +0x1f4
github.com/allegro/mesos-executor.(*Executor).Start(0xc42044c1c0, 0x94a275, 0x10)
	$GOPATH/src/github.com/allegro/mesos-executor/executor.go:176 +0x2c0
main.main()
	$GOPATH/src/github.com/allegro/mesos-executor/cmd/executor/main.go:122 +0x2d3
```

It happen in [executor.Start()](https://github.com/allegro/mesos-executor/blob/v0.11.9/executor.go#L176) becouse `MESOS_SUBSCRIPTION_BACKOFF_MAX` and `MESOS_RECOVERY_TIMEOUT` are only required if `MESOS_CHECKPOINT` is enabled see [`mesos-go executor/config/config.go`](https://github.com/mesos/mesos-go/blob/mesos-1.1.x/api/v1/lib/executor/config/config.go#L85-L89`)

**Comment by AlfredBroda** [comment]
The bug was introduced with #101 maybe we should revert this particular part?
https://github.com/allegro/mesos-executor/blob/master/cmd/executor/main.go#L112-L120

**Comment by janisz** [comment]
No, it was before #101 and introduced at the beginning (ef376ba)

```go
➜  mesos-executor git:(6c4f4dd) MESOS_FRAMEWORK_ID=1 MESOS_EXECUTOR_ID=2 MESOS_DIRECTORY=/tmp/ MESOS_SANDBOX=/tmp/ MESOS_AGENT_ENDPOINT="127.0.0.1" MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD="1ms" MESOS_SUBSCRIPTION_BACKOFF_MAX=1ms MESOS_RECOVERY_TIMEOUT=1ms  target/executor 
INFO[0000] Allegro Mesos Executor (version: 0.11.9)     
INFO[0000] No metric storage specified - using stderr to periodically print metrics 
INFO[0000] Initializing executor with following configuration: 
INFO[0000] AgentEndpoint               = 127.0.0.1      
INFO[0000] Checkpoint                  = false          
INFO[0000] Directory                   = /tmp/          
INFO[0000] ExecutorID                  = 2              
INFO[0000] ExecutorShutdownGracePeriod = 1ms            
INFO[0000] FrameworkID                 = 1              
INFO[0000] RecoveryTimeout             = 0s             
INFO[0000] SubscriptionBackoffMax      = 0s             
INFO[0000] APIPath                     = /api/v1/executor 
INFO[0000] Debug                       = false          
INFO[0000] ServicelogIgnoreKeys        = []             
INFO[0000] StateUpdateBufferSize       = 1024           
panic: illegal value for minWait: 0s

goroutine 1 [running]:
github.com/allegro/mesos-executor/vendor/github.com/mesos/mesos-go/api/v1/lib/backoff.Notifier(0x3b9aca00, 0x0, 0x0, 0xc42034ad80)
	@GOPATH/src/github.com/allegro/mesos-executor/vendor/github.com/mesos/mesos-go/api/v1/lib/backoff/backoff.go:58 +0x1f4
github.com/allegro/mesos-executor.(*Executor).Start(0xc420263180, 0x94ead5, 0x10)
	@GOPATH/src/github.com/allegro/mesos-executor/executor.go:176 +0x2c0
main.main()
	@GOPATH/src/github.com/allegro/mesos-executor/cmd/executor/main.go:117 +0x1ec
```

**Comment by janisz** [comment]
@medzin https://github.com/allegro/mesos-executor/issues/103#issuecomment-376907700
